import { TEAM_ID_BASE } from './constants'

export const enum Team {
  ATL,
  BOS,
  BKN,
  CHA,
  CHI,
  CLE,
  DAL,
  DEN,
  DET,
  GSW,
  HOU,
  IND,
  LAC,
  LAL,
  MEM,
  MIA,
  MIL,
  MIN,
  NOP,
  NYK,
  OKC,
  ORL,
  PHI,
  PHX,
  POR,
  SAC,
  SAS,
  TOR,
  UTA,
  WAS,
}

export const TeamId = new Map<number, number>([
  [Team.ATL, TEAM_ID_BASE + 37],
  [Team.BOS, TEAM_ID_BASE + 38],
  [Team.BKN, TEAM_ID_BASE + 51],
  [Team.CHA, TEAM_ID_BASE + 66],
  [Team.CHI, TEAM_ID_BASE + 41],
  [Team.CLE, TEAM_ID_BASE + 39],
  [Team.DAL, TEAM_ID_BASE + 42],
  [Team.DEN, TEAM_ID_BASE + 43],
  [Team.DET, TEAM_ID_BASE + 65],
  [Team.GSW, TEAM_ID_BASE + 44],
  [Team.HOU, TEAM_ID_BASE + 45],
  [Team.IND, TEAM_ID_BASE + 54],
  [Team.LAC, TEAM_ID_BASE + 46],
  [Team.LAL, TEAM_ID_BASE + 47],
  [Team.MEM, TEAM_ID_BASE + 63],
  [Team.MIA, TEAM_ID_BASE + 48],
  [Team.MIL, TEAM_ID_BASE + 49],
  [Team.MIN, TEAM_ID_BASE + 50],
  [Team.NOP, TEAM_ID_BASE + 40],
  [Team.NYK, TEAM_ID_BASE + 52],
  [Team.OKC, TEAM_ID_BASE + 60],
  [Team.ORL, TEAM_ID_BASE + 53],
  [Team.PHI, TEAM_ID_BASE + 55],
  [Team.PHX, TEAM_ID_BASE + 56],
  [Team.POR, TEAM_ID_BASE + 57],
  [Team.SAC, TEAM_ID_BASE + 58],
  [Team.SAS, TEAM_ID_BASE + 59],
  [Team.TOR, TEAM_ID_BASE + 61],
  [Team.UTA, TEAM_ID_BASE + 62],
  [Team.WAS, TEAM_ID_BASE + 64],
])

export const enum StatsApiParam {
  GAME_ID = 'GameID',
  START_PERIOD = 'StartPeriod',
  END_PERIOD = 'EndPeriod',
  GAME_DATE = 'GameDate',
  LEAGUE_ID = 'LeagueID',
  DAY_OFFSET = 'DayOffset',
}

export type UrlParams = {
  [key in StatsApiParam]?: string | number
}
